# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mitrasree Deb
tagline:          'A Jekyll theme'
description:      'Mitrasree Deb - Personal Website'
url:              https://nimkicodes.github.io/
baseurl:          /

author:
  name:           'Mitrasree Deb'
  url:            https://nimkicodes.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nimkicodes/nimkicodes.github.io
