# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mitrasree Deb
tagline:          'A Jekyll theme'
url:              https://nimkicodes.github.io/
baseurl:          /

author:
  name:           'Mitrasree Deb'
  url:            https://nimkicodes.github.io/

paginate:         5


github:
  repo:           https://github.com/nimkicodes/nimkicodes.github.io
